# Generated by Django 5.1.2 on 2024-11-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_inmate_profile_alter_personnel_profile'),
        ('profiles', '0004_alter_inmate_date_arrested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='archive_by',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='profile',
        ),
        migrations.CreateModel(
            name='ArchiveInmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivepersonnel', to='profiles.inmate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivepersonnel', to='profiles.personnel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Inmate',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
