# Generated by Django 5.1.2 on 2024-11-02 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_remove_personnel_archive_by_remove_personnel_profile_and_more'),
        ('profiles', '0004_alter_inmate_date_arrested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveinmate',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archiveinmate', to='profiles.inmate'),
        ),
    ]
