# Generated by Django 5.1.3 on 2024-11-15 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_archiveinmate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveinmate',
            name='archive_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='archivepersonnel',
            name='archive_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
