# Generated by Django 5.1.2 on 2024-11-01 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(default='default.png', upload_to='thumbnails')),
                ('raw_image', models.FileField(default='default.png', upload_to='raw_images')),
                ('f_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(blank=True, default=None, max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('suffix', models.CharField(blank=True, default=None, max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('legally_separated', 'Legally Separated ')], default='p', max_length=20)),
                ('date_profiled', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_arrested', models.DateField()),
                ('date_committed', models.DateField(blank=True, null=True)),
                ('crime_violated', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix', 'age', 'address', 'civil_status', 'date_profiled', 'date_arrested', 'crime_violated'), name='unique-inmate-profile')],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(default='default.png', upload_to='thumbnails')),
                ('raw_image', models.FileField(default='default.png', upload_to='raw_images')),
                ('f_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(blank=True, default=None, max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('suffix', models.CharField(blank=True, default=None, max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('legally_separated', 'Legally Separated ')], default='p', max_length=20)),
                ('date_profiled', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.CharField(choices=[('pgen', 'Police General, PGEN'), ('pltgen', 'Police Lieutenant General, PLTGEN'), ('pmgen', 'Police Major General, PMGEN'), ('pbgen', 'Police Brigadier General, PBGEN'), ('pcol', 'Police Colonel, PCOL'), ('pltcol', 'Police Lieutenant Colonel, PLTCOL'), ('pmaj', 'Police Major, PMAJ'), ('pcpt', 'Police Captain, PCPT'), ('plt', 'Police Lieutenant, PLT'), ('pems', 'Police Executive Master Sergeant, PEMS'), ('pcms', 'Police Chief Master Sergeant, PCMS'), ('psms', 'Police Senior Master Sergeant, PSMS'), ('pmsg', 'Police Master Sergeant, PMSg'), ('pssg', 'Police Staff Sergeant, PSSg'), ('pcpl', 'Police Corporal, PCpl'), ('pat', 'Patrolman/Patrolwoman, Pat')], default='pat', max_length=10)),
                ('date_assigned', models.DateTimeField()),
                ('date_relieved', models.DateTimeField(blank=True, null=True)),
                ('designation', models.TextField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix', 'age', 'address', 'civil_status', 'date_profiled', 'rank', 'date_assigned', 'designation'), name='unique-personnel-profile')],
            },
        ),
    ]
