# Generated by Django 5.1.2 on 2024-11-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='p_type',
            field=models.CharField(default='personnel', max_length=10),
        ),
        migrations.AddField(
            model_name='personnel',
            name='p_type',
            field=models.CharField(default='personnel', max_length=10),
        ),
    ]
