# Generated by Django 5.1.2 on 2024-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_inmate_p_type_personnel_p_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inmate',
            name='unique-inmate-profile',
        ),
        migrations.AddConstraint(
            model_name='inmate',
            constraint=models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix', 'age', 'address', 'civil_status', 'date_profiled', 'date_arrested', 'date_committed', 'crime_violated'), name='unique-inmate-profile'),
        ),
    ]
