# Generated by Django 5.1.2 on 2024-11-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_inmate_unique_inmate_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='date_arrested',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='date_committed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
