# Generated by Django 5.1.2 on 2024-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_inmate_civil_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='templates')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='personnel',
            name='unique-personnel-profile',
        ),
        migrations.AlterField(
            model_name='inmate',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('legally_separated', 'Legally Separated ')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='p_type',
            field=models.CharField(default='inmate', max_length=10),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('legally_separated', 'Legally Separated ')], default='single', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix', 'age', 'address', 'civil_status', 'date_profiled', 'rank', 'date_assigned', 'date_relieved', 'designation'), name='unique-personnel-profile'),
        ),
    ]
