# Generated by Django 5.1.2 on 2024-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_template_remove_personnel_unique_personnel_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_name',
            field=models.CharField(default='operate', max_length=20),
            preserve_default=False,
        ),
    ]
