# Generated by Django 5.1.2 on 2024-11-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_template_template_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='template',
            new_name='template_file',
        ),
    ]
