# Generated by Django 5.1.2 on 2024-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_template_template_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='raw_image',
            field=models.FileField(upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='raw_image',
            field=models.FileField(upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='thumbnail',
            field=models.FileField(upload_to='thumbnails'),
        ),
    ]
