# Generated by Django 5.1.3 on 2024-11-15 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_inmate_raw_image_alter_inmate_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='date_arrested',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='date_committed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='date_profiled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_assigned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_profiled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_relieved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
