# Generated by Django 5.1.3 on 2024-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_inmate_date_arrested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='address',
            field=models.CharField(default='inmate', max_length=250),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='crime_violated',
            field=models.CharField(default='inmate', max_length=250),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.CharField(default='inmate', max_length=250),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='designation',
            field=models.CharField(default='inmate', max_length=250),
        ),
    ]
