# Generated by Django 5.1.3 on 2024-11-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_inmate_address_alter_inmate_crime_violated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='crime_violated',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='designation',
            field=models.CharField(max_length=250),
        ),
    ]
