# Generated by Django 5.1.3 on 2024-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_inmate_address_alter_inmate_crime_violated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='raw_image',
            field=models.FileField(blank=True, default='default.jpg', upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.jpg', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='raw_image',
            field=models.FileField(blank=True, default='default.jpg', upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.jpg', upload_to='thumbnails'),
        ),
    ]
