# Generated by Django 5.1.3 on 2024-11-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_inmate_raw_image_alter_inmate_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='raw_image',
            field=models.FileField(blank=True, default='default.jpg', upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.jpg', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='raw_image',
            field=models.FileField(blank=True, default='default.jpg', upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.jpg', upload_to='thumbnails'),
        ),
    ]
