# Generated by Django 5.1.3 on 2024-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_inmate_raw_image_alter_inmate_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inmate',
            name='unique-inmate-profile',
        ),
        migrations.RemoveConstraint(
            model_name='personnel',
            name='unique-personnel-profile',
        ),
        migrations.AlterField(
            model_name='inmate',
            name='raw_image',
            field=models.FileField(default='default.png', upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='thumbnail',
            field=models.FileField(default='default.png', upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='raw_image',
            field=models.FileField(default='default.png', upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='thumbnail',
            field=models.FileField(default='default.png', upload_to='thumbnails'),
        ),
        migrations.AddConstraint(
            model_name='inmate',
            constraint=models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix', 'age'), name='unique-inmate-profile'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix'), name='unique-personnel-profile'),
        ),
    ]
