# Generated by Django 5.1.3 on 2024-11-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_inmate_unique_inmate_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='embedding',
            field=models.FileField(blank=True, null=True, upload_to='embeddings'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='embedding',
            field=models.FileField(blank=True, null=True, upload_to='embeddings'),
        ),
    ]
