# Generated by Django 5.1.4 on 2024-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_inmate_embedding_personnel_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.RemoveConstraint(
            model_name='inmate',
            name='unique-inmate-profile',
        ),
        migrations.AddField(
            model_name='inmate',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('legally_separated', 'Legally Separated')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('legally_separated', 'Legally Separated')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.CharField(choices=[('PGEN', 'Police General, PGEN'), ('PLTGEN', 'Police Lieutenant General, PLTGEN'), ('PMGEN', 'Police Major General, PMGEN'), ('PBGEN', 'Police Brigadier General, PBGEN'), ('PCOL', 'Police Colonel, PCOL'), ('PLTCOL', 'Police Lieutenant Colonel, PLTCOL'), ('PMAJ', 'Police Major, PMAJ'), ('PCPT', 'Police Captain, PCPT'), ('PLT', 'Police Lieutenant, PLT'), ('PEMS', 'Police Executive Master Sergeant, PEMS'), ('PCMS', 'Police Chief Master Sergeant, PCMS'), ('PSMS', 'Police Senior Master Sergeant, PSMS'), ('PMSg', 'Police Master Sergeant, PMSg'), ('PSSg', 'Police Staff Sergeant, PSSg'), ('PCpl', 'Police Corporal, PCpl'), ('Pat', 'Patrolman/Patrolwoman, Pat')], default='pat', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inmate',
            constraint=models.UniqueConstraint(fields=('f_name', 'l_name', 'm_name', 'suffix'), name='unique-inmate-profile'),
        ),
    ]
