# Generated by Django 5.1.4 on 2024-12-15 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_delete_template_remove_inmate_unique_inmate_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='date_arrested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
