# Generated by Django 5.1.4 on 2024-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_inmate_date_arrested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.CharField(choices=[('Pat', 'Patrolman/Patrolwoman, Pat'), ('PCpl', 'Police Corporal, PCpl'), ('PSSg', 'Police Staff Sergeant, PSSg'), ('PMSg', 'Police Master Sergeant, PMSg'), ('PSMS', 'Police Senior Master Sergeant, PSMS'), ('PCMS', 'Police Chief Master Sergeant, PCMS'), ('PEMS', 'Police Executive Master Sergeant, PEMS'), ('PLT', 'Police Lieutenant, PLT'), ('PCPT', 'Police Captain, PCPT'), ('PMAJ', 'Police Major, PMAJ'), ('PLTCOL', 'Police Lieutenant Colonel, PLTCOL'), ('PCOL', 'Police Colonel, PCOL'), ('PBGEN', 'Police Brigadier General, PBGEN'), ('PGEN', 'Police General, PGEN'), ('PMGEN', 'Police Major General, PMGEN'), ('PLTGEN', 'Police Lieutenant General, PLTGEN')], default='pat', max_length=10),
        ),
    ]
