# Generated by Django 5.1.4 on 2024-12-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_personnel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='raw_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='raw_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='raw_images'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='thumbnails'),
        ),
    ]
