# Generated by Django 5.1.5 on 2025-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_alter_inmate_raw_image_alter_inmate_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='old_profile',
            field=models.FileField(blank=True, null=True, upload_to='temp'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='old_profile',
            field=models.FileField(blank=True, null=True, upload_to='temp'),
        ),
    ]
