# Generated by Django 5.1.5 on 2025-01-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_inmate_old_profile_personnel_old_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmate',
            old_name='old_profile',
            new_name='new_profile',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='old_profile',
            new_name='new_profile',
        ),
    ]
