# Generated by Django 5.1.5 on 2025-02-01 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_rename_old_profile_inmate_new_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[\\w\\s\\-.,/#]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='f_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='l_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='m_name',
            field=models.CharField(blank=True, default=None, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='suffix',
            field=models.CharField(blank=True, default=None, max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[\\w\\s\\-.,/#]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='f_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='l_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='m_name',
            field=models.CharField(blank=True, default=None, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='suffix',
            field=models.CharField(blank=True, default=None, max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-]+$', inverse_match=True)]),
        ),
    ]
