# Generated by Django 5.1.5 on 2025-02-01 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_alter_inmate_address_alter_inmate_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s*\\-.,/#]+$')]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s*\\-.,/#]+$')]),
        ),
    ]
