# Generated by Django 5.1.5 on 2025-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_alter_inmate_address_alter_personnel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='embedding',
            field=models.FileField(blank=True, null=True, upload_to='embeddings/personnel'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='embedding',
            field=models.FileField(blank=True, null=True, upload_to='embeddings/personnel'),
        ),
    ]
