# Generated by Django 5.1.5 on 2025-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_alter_inmate_embedding_alter_personnel_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='embedding',
            field=models.FileField(blank=True, null=True, upload_to='embeddings/inmate'),
        ),
    ]
