# Generated by Django 5.1.4 on 2024-12-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles_per_page', models.IntegerField(default=20)),
                ('thumbnail_size', models.IntegerField(default=200)),
                ('camera', models.IntegerField(default=0)),
                ('crop_size', models.IntegerField(default=200)),
                ('crop_camera', models.CharField(choices=[('0', 'Do not crop'), ('1', 'Crop')], default='1', max_length=1)),
                ('threshold', models.FloatField(default=1.0)),
                ('search_mode', models.CharField(choices=[('1', 'Embedding (Faster)'), ('0', 'Image')], default='1', max_length=1)),
                ('template_personnel', models.FileField(blank=True, null=True, upload_to='templates')),
                ('template_inmate', models.FileField(blank=True, null=True, upload_to='templates')),
                ('model', models.FileField(blank=True, null=True, upload_to='models')),
            ],
        ),
    ]
