# Generated by Django 5.1.4 on 2024-12-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_defaultsettings_defaultsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultSetting',
            new_name='Setting',
        ),
    ]
