# Generated by Django 5.1.4 on 2024-12-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='clip_camera',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='clip_size',
            field=models.IntegerField(default=400),
        ),
    ]
