# Generated by Django 5.1.4 on 2025-01-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_setting_clip_camera_alter_setting_clip_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='clip_size',
            field=models.IntegerField(default=200),
        ),
    ]
