# Generated by Django 5.1.4 on 2024-12-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_searchimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='crop_size',
            new_name='clip_size',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='crop_camera',
        ),
        migrations.AddField(
            model_name='setting',
            name='clip_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='search_mode',
            field=models.CharField(choices=[('embedding', 'Embedding (Faster)'), ('image', 'Image')], default='embedding', max_length=9),
        ),
    ]
