# Generated by Django 5.1.4 on 2025-01-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_model_setting_model_detection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='input_size',
            new_name='rec_input_size',
        ),
        migrations.AddField(
            model_name='setting',
            name='det_input_size',
            field=models.IntegerField(default=500),
        ),
    ]
