# Generated by Django 5.1.4 on 2025-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_input_size_setting_rec_input_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='det_input_size',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='rec_input_size',
        ),
        migrations.AddField(
            model_name='setting',
            name='bbox_size',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='setting',
            name='input_size',
            field=models.IntegerField(default=105),
        ),
    ]
