# Generated by Django 5.1.4 on 2025-01-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_setting_det_input_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='clip_camera',
            new_name='cam_clipping',
        ),
    ]
