# Generated by Django 5.1.4 on 2025-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_clip_camera_setting_cam_clipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='model_detection',
        ),
        migrations.AddField(
            model_name='setting',
            name='model_embedding_generator',
            field=models.FileField(blank=True, null=True, upload_to='models'),
        ),
    ]
