# Generated by Django 5.1.4 on 2025-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_setting_model_detection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='model_recognition',
        ),
        migrations.AddField(
            model_name='setting',
            name='model_detection',
            field=models.FileField(blank=True, null=True, upload_to='models'),
        ),
    ]
