# Generated by Django 5.1.5 on 2025-01-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_setting_search_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bbox_size',
            field=models.IntegerField(default=300),
        ),
    ]
