# Generated by Django 5.1.5 on 2025-02-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_setting_bbox_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='face_cropping',
            field=models.BooleanField(default=True),
        ),
    ]
