# Generated by Django 5.1.5 on 2025-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_setting_face_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='clip_size',
            field=models.IntegerField(default=300),
        ),
    ]
