# Generated by Django 5.1.6 on 2025-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_setting_clip_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='show_icons',
            field=models.CharField(choices=[(0, 'Show icons'), (1, 'Hide icons')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
