# Generated by Django 5.1.6 on 2025-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_setting_show_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='show_icons',
            field=models.CharField(choices=[('show', 'Show icons'), ('hide', 'Hide icons')], default=0, max_length=4),
        ),
    ]
