# Generated by Django 5.1.3 on 2024-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_threshold', models.FloatField(blank=True, default=1.0, null=True)),
                ('default_camera', models.IntegerField(blank=True, default=1, null=True)),
                ('crop_camera', models.IntegerField(choices=[('0', 'Do not crop'), ('1', 'Crop')], default='0', max_length=1)),
                ('default_search_method', models.CharField(choices=[('0', 'Embedding (Faster)'), ('1', 'Image')], default='0', max_length=1)),
                ('personnel_template', models.FileField(blank=True, null=True, upload_to='templates')),
                ('inmate_template', models.FileField(blank=True, null=True, upload_to='templates')),
            ],
        ),
    ]
