# Generated by Django 5.1.3 on 2024-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatesetting',
            name='crop_camera',
            field=models.CharField(choices=[('0', 'Do not crop'), ('1', 'Crop')], default='0', max_length=1),
        ),
    ]
