# Generated by Django 5.1.3 on 2024-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_operatesetting_crop_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatesetting',
            name='default_profiles_per_page',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='operatesetting',
            name='default_thumbnail_size',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
