# Generated by Django 5.1.3 on 2024-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_operatesetting_default_profiles_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatesetting',
            name='default_crop_size',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
