# Generated by Django 5.1.3 on 2024-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_operatesetting_default_crop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatesetting',
            name='default_search_method',
            field=models.CharField(choices=[('1', 'Embedding (Faster)'), ('0', 'Image')], default='1', max_length=1),
        ),
    ]
