# Generated by Django 5.1.3 on 2024-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_operatesetting_default_search_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatesetting',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='model'),
        ),
    ]
