# Generated by Django 5.1.3 on 2024-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_operatesetting_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatesetting',
            name='crop_camera',
            field=models.CharField(choices=[(0, 'Do not crop'), (1, 'Crop')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='operatesetting',
            name='default_search_method',
            field=models.CharField(choices=[(1, 'Embedding (Faster)'), (0, 'Image')], default='1', max_length=1),
        ),
    ]
