# Generated by Django 5.1.3 on 2024-11-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_operatesetting_crop_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatesetting',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='models'),
        ),
    ]
