# Generated by Django 5.1.4 on 2024-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_operatesetting_crop_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatesetting',
            name='default_camera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operatesetting',
            name='default_crop_size',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='operatesetting',
            name='default_profiles_per_page',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='operatesetting',
            name='default_threshold',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='operatesetting',
            name='default_thumbnail_size',
            field=models.IntegerField(default=200),
        ),
    ]
